site_name: "L5: A Processing Library in Lua"
site_url: https://l5lua.org
validation:
  absolute_links: ignore
  nav:
    omitted_files: ignore
    not_found: ignore
    absolute_links: ignore
theme:
  name: material
  palette:
    primary: gold
    accent: blue
  logo: assets/L5-logo-blob.png
  font: false
  favicon: assets/L5-logo-blob.png
  features:
    - navigation.indexes
    - content.code.copy          # Copy button
    - content.code.select        # Allow selecting code
extra_css:
 - stylesheets/extra.css
extra:
  generator: false
hooks:
  - hooks/image_fallback.py # fallback from webp to jpg on browsers without webp 
nav:
  - Welcome to L5: index.md
  - Download: download.md
  - L5 for Processing-p5.js programmers: L5-for-processingp5.md
  - Reference: 
    - Reference Summary: reference/index.md
    - Shape: reference/#shape
    - Color: reference/#color
    - Typography: reference/#typography
    - Image: reference/#image
    - Media: reference/#media
    - Transform: reference/#transform
    - Environment: reference/#environment
    - Rendering: reference/#rendering
    - Math: reference/#math
    - IO: reference/#io
    - Events: reference/#events
    - Data: reference/#data
    - Structure: reference/#structure
    - Constants: reference/#constants
    - Foundation: reference/#foundation
  - Tutorials: tutorials/index.md
  - Examples: examples/index.md
  - Bug Reports: bug-reports.md
  - Contributing: contributing.md
  - For developers: how.md
  - Copyleft: copyleft.md
